### ISSUE TITLE
Import as Package

### ISSUE THREAD

**Issue by abegehr** [chipweinberger/dart_melty_soundfont#1]
Thank you for building and publishing this package!
I'm unable to import any resources from the package after install in in pubspec.yaml.
The example references a non-package import: https://pub.dev/packages/dart_melty_soundfont#example
I'm looking for a package import like referenced here: https://dart.dev/guides/libraries/create-library-packages#importing-library-files

**Comment by chipweinberger** [comment]
Ya i was wondering if the files needed to be ina  “lib” and not a “src”
folder. Maybe that’s it.

Try changing the folder name and let me know if that works. First time
publishing a package.

**Comment by chipweinberger** [comment]
pushed a change. pretty sure thats the issue. lmk.

**Comment by chipweinberger** [comment]
My example needs to have its import statements updated as well.
```
import 'package:dart_melty_soundfont/synthesizer.dart';
import 'package:dart_melty_soundfont/synthesizer_settings.dart';
import 'package:dart_melty_soundfont/audio_renderer_ex.dart';
import 'package:dart_melty_soundfont/array_int16.dart';
```

**Comment by chipweinberger** [comment]
should be all fixed now. lmk.

**Comment by abegehr** [comment]
Awesome, thanks @chipweinberger. Importing works now 👍
