### ISSUE TITLE
Exception occurs for some sound font files

### ISSUE THREAD

**Issue by postacik** [chipweinberger/dart_melty_soundfont#12]
[meltysynth](https://github.com/sinshu/meltysynth) library raises an exception for some sound font files.

It was fixed in the last commit.

Can you please apply the same fix to your library?

https://github.com/sinshu/meltysynth/issues/14#issuecomment-1114255892

**Comment by chipweinberger** [comment]
no problem.

e4c3db7e1cfcce708a96b0df6a66a150388f204c

**Comment by postacik** [comment]
Thanks :)
