### ISSUE TITLE
A bug due to a typo

### ISSUE THREAD

**Issue by sinshu** [chipweinberger/dart_melty_soundfont#13]
A bug due to a typo was found in the C# version.
It seems that the Dart version also has this bug.
Please check this issue: https://github.com/sinshu/meltysynth/issues/15

https://github.com/chipweinberger/DartMeltySoundFont/blob/914b72fbe09fe8e6918bf4c37ca4968ecc2db6aa/lib/synthesizer.dart#L217-L223

**Comment by chipweinberger** [comment]
thanks for telling me! will fix!

**Comment by chipweinberger** [comment]
https://github.com/chipweinberger/DartMeltySoundFont/commit/59b6bb993974a8f417ca34487791bdf6765ee469
