### ISSUE TITLE
Midi file support

### ISSUE THREAD

**Issue by postacik** [chipweinberger/dart_melty_soundfont#14]
Hi,
I added midi file sequencer feature in [my fork](https://github.com/postacik/DartMeltySoundFont).

I tried to obey your style of conversion from C#.

The code is not battle tested but it works with my test midi files as you can see in the video below:

https://user-images.githubusercontent.com/3977227/167107533-c0a27b20-8b96-4be5-9d10-d0bec5dfa44a.mp4

I hope it would help you to complete the library :)

**Comment by chipweinberger** [comment]
thanks!!!

Looking forward to testing it out :)

**Comment by chipweinberger** [comment]
can you make a pull request with the changes? thanks

**Comment by postacik** [comment]
I modified my fork beyond the scope of this library. I'll check if I can create a new fork and then create a pull request.

**Comment by jtkeyva** [comment]
@postacik any chance of that PR? this would make a cool example thx

**Comment by jtkeyva** [comment]
@chipweinberger thanks for the cool package. any midi implementation for it? i want to record and playback midi

**Comment by amuhaimin02** [comment]
Hi, if anyone is still interested, I added the missing MIDI file support on my fork and made a PR for it. Check it out

[PR link](https://github.com/chipweinberger/dart_melty_soundfont/pull/29)

**Comment by chipweinberger** [comment]
merged.

**Comment by jtkeyva** [comment]
cool stuff thanks. fyi, the example on web it hangs on initializing
