### ISSUE TITLE
Rending audio off of the main thread

### ISSUE THREAD

**Issue by wsievern** [chipweinberger/dart_melty_soundfont#21]
Has anyone figured out a way to do this?

For me, when intensive UI operations occur while audio is rendering there are clicks during playback

**Comment by chipweinberger** [comment]
sure you can render with a dart isolate.

but submitting the audio with `flutter_pcm_sound` will still happen using a platform channel which is main thread i think so you'll want to keep your UI responsive 

---

**edit**: actually maybe responsive UI is not necessary 
see: https://github.com/flutter/flutter/issues/13937 
see: https://medium.com/flutter/introducing-background-isolate-channels-7a299609cad8

**Comment by wsievern** [comment]
Looking into this! Thx
