### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by Plumillon** [chipweinberger/dart_melty_soundfont#26]
It would be nice to have web support.
Are you planning to implement it?

**Comment by chipweinberger** [comment]
nope

i recommend forking

**Comment by chipweinberger** [comment]
it already supports web

this is a pure dart package with no dependencies

**Comment by Plumillon** [comment]
Awesome!
Didn't see the badge on the plugin page so I wondered.

Thx for your work 👍🏾.
