### ISSUE TITLE
Web Support

### ISSUE THREAD

**Issue by nathanblanchard12** [chipweinberger/dart_melty_soundfont#7]
No web support. Would be super cool if had one. I couldn't find anyone with web support. :(

**Comment by chipweinberger** [comment]
It does support web. This is pure dart, with no Flutter dependency. There's no UI. Just algos.

Feel free to use on web.

**Comment by chipweinberger** [comment]
Seems like a bug that pub.dev does not show web support. AFAIK, anything that is pure dart (no Flutter dependency) automatically supports web.

**Comment by nathanblanchard12** [comment]
Ok. I'll check it out thanks
