### ISSUE TITLE
Example project For Web

### ISSUE THREAD

**Issue by nathanblanchard12** [chipweinberger/dart_melty_soundfont#8]
Hello can you add an example to the project. It would be easier to figure out if it works. I might be using it wrong but I hear no audio. I am not sure if it is my sf2 file or computer or settings

**Comment by chipweinberger** [comment]
This library does not output audio. It generates waveforms. There is an example in the readme for generating the waveforms. 

If you want to hear it, you need to pass the waveform to a plugin with PCM sound output (android & iOS) like: https://pub.dev/packages/raw_sound

You said you are on web, maybe you can use this. not sure. https://api.dart.dev/stable/2.16.1/dart-web_audio/dart-web_audio-library.html

docs:
https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API

**Comment by jtkeyva** [comment]
still trying to get this running on web. any help appreciated. would this work? https://pub.dev/packages/flutter_soloud/versions/2.1.7
